---
- name: setup nginx
  hosts: localhost
  vars: 
    nginx_port: 8080
  tasks:
    - name: installing nginx
      yum:
        name: nginx
        state: latest

    - name: copy config
      template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - start nginx

          #    - name: starting nginx
          #      service:
          #        name: nginx
          #        state: started
          #        enabled: yes


  handlers:
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes

